#pragma once

#include "NativeGameplayTags.h"

namespace PDGameplayTags
{
	/** Input Tags **/
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Equip_Slot1);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Equip_Slot2);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Equip_Slot3);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Equip_Slot4);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Unequip);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Fire);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Reload);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_ADS);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_ChangeFireMode);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Skill1);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Skill2);

	/** Player Tags **/
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Weapon_Equip);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Weapon_Unequip);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Weapon_Fire);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Weapon_Reload);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Weapon_ADS);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Weapon_ChangeFireMode);

	/** Event Tags **/
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Weapon_EquipRequest);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Weapon_EquipConfirm);
	
	/** SetByCaller Tags **/
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Weapon_Damage);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Weapon_FireInterval);
	PROJECTD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Weapon_Fire);
}